from tkinter import*
rt=Tk()
rt.title("frame example")
frame=Frame(rt,borderwidth=2,relief=SOLID)
frame.pack(padx=50,pady=40)
label=Label(frame,text="this is inside frame")
label.pack()
button=Button(frame,text="click me")
button.pack()
entry=Entry(frame)
entry.pack()
inner_frame=Frame(frame,borderwidth=2,relief=SOLID)
inner_frame.pack(padx=20,pady=30)
label2=Label(inner_frame,text="this is inside frame")
label2.pack()
rt.mainloop()